### ISSUE TITLE
Heroku instance currently unavailable

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-walk-in#1]
http://elcid-walkin.herokuapp.com/accounts/login/?next=/

Generates:

Application Error
An error occurred in the application and your page could not be served. Please try again in a few moments.

If you are the application owner, check your logs for details.

Not sure why!

**Comment by davidmiller** [comment]
That instance is no longer in active use !

Try elcid-opat instead.

closes #1

On 9 January 2015 at 16:07, Michael Marks <notifications@github.com> wrote:

> http://elcid-walkin.herokuapp.com/accounts/login/?next=/
>
> Generates:
>
> Application Error
> An error occurred in the application and your page could not be served.
> Please try again in a few moments.
>
> If you are the application owner, check your logs for details.
>
> Not sure why!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhealthcare/opal-walk-in/issues/1>.
>



-- 
Love regards etc

David Miller
http://www.deadpansincerity.com
@thatdavidmiller <http://twitter.com/thatdavidmiller>
07854 880 883
