### ISSUE TITLE
Strongly Consider Forcing Diagnosis at Removal From Walk-In Review

### ISSUE THREAD

**Issue by michaeledwardmarks** [openhealthcare/opal-walk-in#24]
Currently we say: No Diagnosis: Add OR continue anyway
Need to see how frequently now recoded.

**Comment by michaeledwardmarks** [comment]
Suggest making this a bit like the Inpatient Discharge QC flow.

**Comment by davidmiller** [comment]
Closing in favour of openhealthcare/elcid#1063
