### ISSUE TITLE
Symptoms does not restrict text to 255 chars.

### ISSUE THREAD

**Issue by davidmiller** [openhealthcare/opal-walk-in#9]
This means we get ugly "Item could not be saved" errors rather than client-side validations.

**Comment by michaeledwardmarks** [comment]
Can we increase the character limit at the same time as error prompting?

**Comment by davidmiller** [comment]
Nope - that can come later.

**Comment by michaeledwardmarks** [comment]
Wow people must be writing letters in that box to get it to max out!
